project_root: "/var/www/html/blraudiovisuel"
git_version: "master"
composer_path: "/usr/local/bin/composer"
parameters:
    database_host: "mysql_database"
    database_port: "null"
    database_name: "blraudiovisuel"
    database_user: "root"
    database_password: "{{ database_password }}"
    mailer_transport: "smtp"
    mailer_host: "127.0.0.1"
    mailer_user: "null"
    mailer_password: "null"
    secret: "ThisTokenIsNotSoSecretChangeIt"
